---
title: "SS2864GroupProj"
author: "Rui Zhu"
date: "11/23/2020"
output: html_document
---

\newpage
# Andern's work 11/24/20
```{r}
library(magrittr) 
library(ggplot2)
library(mapcan)
library(dplyr)
#data from 1/22/20 till 11/23/20
df <- read.csv(file = 'time_series_covid19_confirmed_global.csv')
head(df)
```
#And then we trim the dataframe a little bit before we utilize it for the first task 
```{r}
df = df[-(42:43),]
df =df[40:52,]
print(df)
df

df = df[c("Province.State","X11.23.20")]
#use mapcan
pr_map <- mapcan(boundaries = province,
       type = standard) %>%
  ggplot(aes(x = long, y = lat, group = group))
pr_map
pr_map <- pr_map +
  geom_polygon() +
  coord_fixed()
pr_geographic <- mapcan(boundaries = province,
       type = standard)


pr_geographic <- inner_join(pr_geographic, 
           df, 
           by = c("pr_english" = "Province.State"))
pr_geographic %>%
  ggplot(aes(x = long, y = lat, group = group, fill = X11.23.20)) +
  geom_polygon() +
  coord_fixed() +
  theme_mapcan() +
  scale_fill_viridis_c(name = "X11.23.20") +
  ggtitle("Canadian Population by Province")
rlang::last_error()
pop_2017 <- mapcan::province_pop_annual %>%
  filter(year == 2017)
pop_2017
#use r data to load the dataframe of the crime about...
x
```